#!/bin/bash

# This script starts a google search of the selected phrase
# Put it on a shortcut like SUPER+G
# Created by Rene Kiupel

xdg-open http://google.de/search?q=$(xsel -o | sed "s/[ \t]/%20/g")
