#!/bin/bash

# This script starts a google search with google-chrome of the selected phrase
# Put it on a shortcut like WIN+g
# Feel free to use this script
# Created by Rene Kiupel

google-chrome http://google.de/search?q=$(xsel -o | sed "s/[ \t]/%20/g")
